Feature/plugin filter editor
UST-QuAntiL/qhana-ui pull request #48
Opened 2023-07-11 08:15 UTC by infacc

2023-07-11 14:28 UTC, buehlefs commented on src/app/components-small/plugin-filter-editor/plugin-filter-editor.component.ts
> +            this.filterObject = JSON.parse(filterValue);
catch JSON paring errors that could happen here

2023-07-14 14:58 UTC, buehlefs commented on src/app/components-small/plugin-filter-node/plugin-filter-node.component.ts
> +        const type = Object.keys(filter)[0];
If you want to, you could add an active warning to the code:
```suggestion
        const filterKeys = Object.keys(filter)
        if (filterKeys.length != 1) {
            console.error("Filters with more than one attribute are not supported!");
        }
        const type = filterKeys[0];
```

2023-07-14 14:58 UTC, buehlefs commented on src/app/components-small/plugin-filter-node/plugin-filter-node.component.ts
> +        if (type !== 'and' && type !== 'or' && type !== 'name' && type !== 'tag' && type !== 'version') {
Create a static set of allowed filter types and test if type is in that set (or refactor this test out into a method).
Even if this is probably the most optimized version it is also hard to read and maintain.

2023-07-14 14:58 UTC, buehlefs commented on src/app/components-small/plugin-filter-node/plugin-filter-node.component.ts
> +        const isLeaf = type !== 'and' && type !== 'or';
It is probably a good idea to add a comment to remind future developers why this (and other locations) do not test for the "not" filter. The best location for this is probably the definition of the type "FilterType"

2023-07-14 14:58 UTC, buehlefs commented on src/app/components-small/template-details/template-details.component.html
> +    <qhana-plugin-filter-editor [tabLink]="tabLink" (filterEmitter)="onFilterChange($event)"></qhana-plugin-filter-editor>
```suggestion
    <qhana-plugin-filter-editor [tabLink]="tabLink" (filterEmitter)="filterString = $event"></qhana-plugin-filter-editor>
```

2023-07-18 17:08 UTC, infacc commented on src/app/components-small/plugin-filter-node/plugin-filter-node.component.html
> +    <div *ngIf="isFilterEmpty()" class="create-buttons">
This is meant for empty filters (`{}`). I.e. when a tab is newly created. The HTML class name `create-buttons` is misleading, I changed it to `set-buttons`.

2023-07-19 21:02 UTC, infacc commented on src/app/components-small/plugin-filter-node/plugin-filter-node.component.ts
> +        const filter = this.filterObject.not ?? this.filterObject;
Now deep copies are used. E.g. https://github.com/UST-QuAntiL/qhana-ui/blob/16dd6a53a3e6ab32cabb7e66e0f2e14998122ae0/src/app/components-small/plugin-filter-node/plugin-filter-node.component.ts#L42

2023-07-19 21:04 UTC, infacc commented on src/app/components-small/plugin-filter-node/plugin-filter-node.component.ts
> +        this.filterOut.emit(filter);
That wasn't intentional and is now fixed.

2023-07-20 07:54 UTC, buehlefs commented on src/app/components-small/plugin-filter-node/plugin-filter-node.component.ts
> +        const filter = this.filterObject.not ?? this.filterObject;
This should work. Shallow copies would also have worked if they cover every level of nesting that is inside the same filter node, as each node does these copies.

2023-07-20 08:28 UTC, buehlefs reviewed
Looks good, but there is another bug with the tab editing form. The form does not contain the name or description of an existing tab (the sort key may have the same problem)

2023-07-20 12:40 UTC, infacc commented
The form didn't display the tab name/description/sortKey since I forgot to remove the filterString from the FormGroup. Now it works.

2023-07-20 21:01 UTC, infacc commented
I added 2 more things:
- A reload button for the filter editor, which resets the filter editor to the saved filter.
- A JSON validator for the JSON editor (of the filter string). This doesn't validate the filter string but complains if the user enters invalid JSON.

2023-07-21 08:42 UTC, buehlefs requested changes
Just one cosmetic/formulation change

2023-07-21 08:42 UTC, buehlefs commented on src/app/components-small/plugin-filter-editor/plugin-filter-editor.component.html
> +            Reload Filter
```suggestion
            Revert Changes
```

2023-07-21 08:42 UTC, buehlefs commented on src/app/components-small/plugin-filter-editor/plugin-filter-editor.component.html
> +            <mat-icon>refresh</mat-icon>
This is a decorative icon, so it should be hidden from screen readers: <https://material.angular.io/components/icon/overview#decorative-icons>

2023-07-21 12:05 UTC, buehlefs approved these changes

2023-07-21 12:06 UTC, merged